### ISSUE TITLE
Mistake in ArrayStack.java clear()

### ISSUE THREAD

**Issue by RKAbdul** [danielnd7/Data-Structures#1]
In the clear function, you are putting elements to null,
`
@Override
    public void clear() {
        elements = null;
        size = 0;
    }
`
 however you can not do that, Because it removes the reference to the array in itself after which working with the array will cause an NulllPointerException in future.
The correct way to do it would be, putting the elements to nulll:
`
  @Override
  public void clear() {
      for (int i = 0; i < size; i++) {
          elements[i] = null;
      }
      size = 0;
  }`

**Comment by danielnd7** [comment]
Thank you very much for letting mi know about this mistake Abdul! Now it is correct :)
